title: Touch-free tap
hero_image: images/banner.png
description: Use a Raspberry Pi Pico, an ultrasonic sensor, a relay, and a pump to create a hands-free tap
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Mount the distance sensor
    completion:
      - engaged
  - title: Wire the sensor circuit
  - title: Measure distance with picozero
    completion:
      - internal
  - title: Wire the relay and pump
  - title: Program the relay and pump
    completion:
      - external
  - title: Challenge
    challenge: true
